### ISSUE TITLE
Referencing type ~> error at import

### ISSUE THREAD

**Issue by kboghe** [devindg/pybuc#14]
Hi there,

First of all: thanks for the package and the hard work you've put into this! This is probably the most feature-rich bsts package available on Python. However, and this might seem like a silly issue, Python throws an error when I import your package. More specifically, it seems like references to tuples are interpreted as a type instead as a parameter in the buc.py file. For example, on line 535 (buc.py), my environment throws an [TypeError: 'type' object is not subscriptable] error.

I've checked the dependencies and they seemed (?) okay. I'm running this on Python 3.8 instead of 3.9 though, but it seems unlikely that this is an issue (or perhaps it is, of course). Moreover, I installed an earlier version of pybuc and the error hasn't popped there. When checking the earlier versions of this function, it's clear the lag_seasonal parameter wasn't subscripted then but it is now (tuple**[bool**]). 

Any idea how to fix this (and why Python throws this error when it clearly worked fine for you ;))?

Many thanks!

**Comment by kboghe** [comment]
Ahum, nevermind, it **is** because of the older Python version. Direct references to type objects like that are allowed from >= Python 3.9. Issue closed! :)

**Comment by devindg** [comment]
Sorry for not getting to this sooner, @kboghe . Another user alerted me to this issue as well, and you're right, it has to do with an older version of Python (< 3.9). I've since updated the *.toml file to require 3.9 or 3.10. I hope this resolves the issue for other users as well. The latest version of the package is now 0.14.14. Thanks for your support!

**Comment by kboghe** [comment]
No problem at all, devindg. Thanks again for your effort, best of luck and have a great day. :)
