### ISSUE TITLE
Accessing the Model Equation

### ISSUE THREAD

**Issue by tim-mcwilliams** [devindg/pybuc#51]
Hi! 

Is there anyway to print out the model equation after building the model? Trying to conduct a sensitivity analysis on the model and need to access the formal equation.

Cheers!

**Comment by devindg** [comment]
Hi @tim-mcwilliams! When you say the model equation, I assume you mean y(t) = Z(t)*a(t), where Z(t) is the observation matrix and a(t) is the state vector. For example, if you only specified a stochastic level component, Z(t) = [1] and a(t) = level(t-1) + level_error(t). Is this what you're after?

**Comment by tim-mcwilliams** [comment]
Hmm, I'm pretty sure that would work. 

Some context as to why I'm asking. Wanting to use this package ([sensitivity](https://nickderobertis.github.io/sensitivity/overview.html)) to conduct sensitivity analyses to assess the robustness of the UC model.

Have you tried anything like that before with this package??

**Comment by devindg** [comment]
I've not used this before, but it looks like it creates pairwise permutations of the data to assess robustness of the model to different inputs. What inputs are you trying to vary? Regression variables? Priors? Components?

**Comment by tim-mcwilliams** [comment]
yea exactly, it basically assess how stable the model is if inputs were to change to some degree. For this use case I would be looking to vary the Regression variables.

**Comment by devindg** [comment]
Maybe I'm overthinking this, but there are two ways to assess sensitivity with respect to regression variables. One way is to estimate a new set of parameters, treating the different variable permutations as distinct model instantiations. The other way is to estimate your model with the original data, and then plug in your permuted variables for different in-sample and forecasted predictions. Both methods assume the model specification stays the same, i.e., the component specification is the same. 

The first approach will give you different posteriors for the parameters. The second approach will keep the posterior parameter values the same.

Which of the above are you trying to achieve? If it's the second approach, then I will need to add code to accommodate that.

**Comment by tim-mcwilliams** [comment]
Sorry for the delayed response here!

I would say the second approach is what I would be looking for. That way we will be able to test different in-sample and forecasted predictions to see how variable the model is when handling different swings in the IV vars.

**Comment by devindg** [comment]
Hi @tim-mcwilliams! I will start working on this this week. Most likely it will be an augmentation of the posterior_predictive_distribution() method to allow for different values of the predictors. The forecast() method can already accept whatever values you want/have for the predictors.

**Comment by tim-mcwilliams** [comment]
Awesome, looking forward to the new feature!

**Comment by devindg** [comment]
Hey @tim-mcwilliams. A new version, 0.18.2, has been released to reflect this new feature. Note that I changed the name of the method `posterior_predictive_distribution()` to `post_pred_dist()` for brevity. Example fake code:

```
from pybuc.buc import BayesianUnobservedComponents as BUC
burn = 100
mod = BUC(response=y, predictors=x_orig, level=True, seed=123)
mod.sample(1000)
ppd_orig = mod.post_pred_dist(burn=burn)
ppd_new = mod.post_pred_dist(predictors=x_new, burn=burn)
yhat_orig_mean = np.mean(ppd_orig, axis=0)
yhat_new_mean = np.mean(ppd_new, axis=0)
```

The `post_pred_dist()` method returns an array of dimension (s, n - num_first_obs_ignore), where s is the number of non-burned posterior samples and n is the number of observations for the response. By default, `num_first_obs_ignore=None`, in which case the first few observations will be ignored for computing the posterior predictive distribution. You can read more about this argument and what it means in the documentation. Briefly, though, some of the first observations are ignored by default because the Kalman filter requires initialization, which in turn means the first few predictions from the Kalman filter may be unreliable. If you want to keep all observations, you can pass `num_first_obs_ignore=0`.

**Comment by devindg** [comment]
> Awesome, looking forward to the new feature! 

Hey @tim-mcwilliams, did the above resolve your issue?

**Comment by tim-mcwilliams** [comment]
@devindg, Had to take a break on this research project but will be picking it back up later this week. Will try your solution then and let you know how it went.

**Comment by tim-mcwilliams** [comment]
@devindg , this is exactly what I was looking for from this issue.  Nice and easy to use too! Thanks so much 👍🏼

**Comment by tim-mcwilliams** [comment]
Closing!
