### ISSUE TITLE
plot_trace not working???

### ISSUE THREAD

**Issue by tim-mcwilliams** [devindg/pybuc#59]
Hi again, @devindg !! 

Running through some model iterations and wanted to see what the trace plots are looking like. I saw in `buc.py` that there is a function for `plot_trace`, but when trying to implement its throwing an error. 

```
# Plot trace of posterior
bayes_uc.plot_trace(burn=mcmc_burn)
plt.show()
```

Gives

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[275], line 2
      1 # Plot trace of posterior
----> 2 bayes_uc.plot_trace(burn=mcmc_burn)
      3 plt.show()

AttributeError: 'BayesianUnobservedComponents' object has no attribute 'plot_trace'
```

**Comment by devindg** [comment]
When you say buc.py, are you talking about the version online or your local version? This function was introduced on June 12, 2023.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Tim McWilliams ***@***.***>
Sent: Tuesday, September 26, 2023 11:29:46 AM
To: devindg/pybuc ***@***.***>
Cc: devindg ***@***.***>; Mention ***@***.***>
Subject: [devindg/pybuc] plot_trace not working??? (Issue #59)


Hi again, @devindg<https://github.com/devindg> !!

Running through some model iterations and wanted to see what the trace plots are looking like. I saw in buc.py that there is a function for plot_trace, but when trying to implement its throwing an error.

# Plot trace of posterior
bayes_uc.plot_trace(burn=mcmc_burn)
plt.show()


Gives

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[275], line 2
      1 # Plot trace of posterior
----> 2 bayes_uc.plot_trace(burn=mcmc_burn)
      3 plt.show()

AttributeError: 'BayesianUnobservedComponents' object has no attribute 'plot_trace'
