### ISSUE TITLE
Accessing the posterior of each state component

### ISSUE THREAD

**Issue by tim-mcwilliams** [devindg/pybuc#61]
Hi @devindg!! 

Was looking through the package here and was wondering if there is a way for me to access the posterior of each state component independently. I know the `plot_components()` function plots them out for you, but I am interested in the raw data that backs up those charts.

Is there a built in method for accessing each state component separately? 

Asking here because I want to try and use this decomposition to calculate what the base response is taking out the white noise, seasonality, and regression effects. In other words, what does the distribution of the response look like over time without those components contributing to it?

**Comment by devindg** [comment]
Hey Tim,

Sorry for the late response. I'll release a new version of the package soon so that you can access the posterior for these components easily.

**Comment by devindg** [comment]
@tim-mcwilliams 

New version 0.18.6 is out. It has a method called components(). This will return a dictionary with each component's posterior distribution.
