### ISSUE TITLE
time varying coefficients

### ISSUE THREAD

**Issue by tim-mcwilliams** [devindg/pybuc#66]
Hi @devindg,

Hope all is well!!

Was looking into the `bsts` package in `R` that you built this package off of. I found in the CRAN documentation that the `bsts` package can incorporate time varying coefficients into the state component, "If predictor variables are present, the regression coefficients are fixed (as opposed to time varying, though time varying coefficients might be added as state component)". 

If I have predictor variables in my UC model but wanted to add in time varying coefficients into the state component, could that be done in this package?

If so, can you point me to the method that do so?

[bsts-cran](http://cran.nexr.com/web/packages/bsts/bsts.pdf) - Page 24

As always, thanks for the guidance! 
-Tim

**Comment by devindg** [comment]
Hi @tim-mcwilliams! Unfortunately, that feature is not available. I may add that in later but don't have an ETA.
